version: '3'

services:

  api:
    image: rm338568/ubuntu-api
    ports:
      - "10050:"10050"
    depends_on:
      - rm338568/zabbix-appliance
    deploy:
      replicas: 1
      #update_config:
      #  parallelism: 1
      #  delay: 10is
      mode: replicated
      restart_policy:
        condition: on-failure

  zabbix-appliance:
    image: rm338568/zabbix-appliance
    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - db-data:/var/lib/zabbix
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure

volumes:
  db-data:
